## Introduction to TensorFlow ## 

(Much of this material is originally from cs224d TensorFlow tutorial by Bharath Ramsundar)

![TensorFlow logo](images/tensorflow.png)

TensorFlow provides primitives for defining functions on tensors and automatically computing their derivatives. 

* TensorFlow is a deep learning library for Python that has been recently open-sourced by Google. 
* TensorFlow has better support for distributed systems than many other competing libraries (i.e. Theano). 
* Keras (next tutorial) is a  high-level library that builds on TensorFlow. 


## What is a tensor? ##

![tensor definition](images/tensor_definition.png) 

## There are some similarities between TensorFlow and Numpy ##

* Both TensorFlow and Numpy are N-d array libraries 
* Numpy does not have methods to create tensor functions and automatically compute derivatives. 
* Numpy does not have GPU support, but TensorFlow does. 

### Numpy: ###


In [2]:
import numpy as np 

In [3]:
a=np.zeros((2,2)); b=np.ones((2,2))

In [4]:
np.sum(b,axis=1)

array([ 2.,  2.])

In [5]:
a.shape

(2, 2)

In [6]:
np.reshape(a,(1,4))

array([[ 0.,  0.,  0.,  0.]])

### Same commands in TensorFlow:###

In [7]:
import tensorflow as tf

In [8]:
tf.InteractiveSession()

We just created an interactive Session. A Session object encapsulates the environment in which tensors are evaluated. 

In [9]:
 a = tf.zeros((2,2)); b = tf.ones((2,2))

In [10]:
 tf.reduce_sum(b, reduction_indices=1).eval()

array([ 2.,  2.], dtype=float32)

In [11]:
 a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

We see above that TensorShape behaves like a Python  tuple. 

In [12]:
 tf.reshape(a, (1, 4)).eval()

array([[ 0.,  0.,  0.,  0.]], dtype=float32)

We can build a Numpy to TensorFlow dictionary: 
![Numpy To TensorFlow dictionary](images/numpy_to_tensorflow.png)

## TensorFlow requires explicit evaluation ##
TensorFlow computations define a computation graph that has no value until evaluated

In [13]:
#in Numpy: 
a=np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [14]:
#but in TensorFlow
ta=tf.zeros((2,2))
print(ta)

Tensor("zeros_1:0", shape=(2, 2), dtype=float32)


In [15]:
#now, we evaluate the computation graph: 
print(ta.eval())

[[ 0.  0.]
 [ 0.  0.]]


## More on Sessions ##

In [16]:
a=tf.constant(5.0)
b=tf.constant(6.0)
c=a*b 
with tf.Session() as sess: 
    print(sess.run(c))
    print(c.eval())


30.0
30.0


So we observe that ```c.eval()``` is a compact way of executing ```sess.run(c)``` in the currently active session.
```tf.InteractiveSession()``` is convenient syntax for keeping a default session open in iPython. 